server:
  port: 8080

spring:
  datasource:
    username: novastore_user
    password: Yg69BP96gyB8L2HR1rVv9zt8UMebe5Ae
    url: jdbc:postgresql://dpg-clpi5o146foc73cgjpdg-a.oregon-postgres.render.com:5432/novastore
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: omonov2006omonov@gmail.com
    password: wkocegbefwfizukv
    properties:
      mjaail:
        smtp:
          auth: true
      mail:
        smtp:
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

jwt:
  secret:
    key: 343243432432970943248034738493482742437324FG1
  access:
    expiry: 300000
  refresh:
    expiry: 300000

forDataLoader: never