server:
  port: 8080

spring:
  datasource:
    username: *
    password: *
    url: *
    driver-class-name: org.postgresql.Driver
#  datasource:
#      username: *
#      driver-class-name: org.postgresql.Driver
#      password: *
#      url: jdbc:postgresql://localhost:5432/nova_store
  mail:
    host: smtp.gmail.com
    port: 587
    username: omonov2006omonov@gmail.com
    password: *
    properties:
      mjaail:
        smtp:
          auth: true
      mail:
        smtp:
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

jwt:
  secret:
    key: 343243432432970943248034738493482742437324FG1
  access:
    expiry: 300000000
  refresh:
    expiry: 300000

forDataLoader: never

