server:
  port: 25060

spring:
  datasource:


    username: doadmin
    password: AVNS_yz_TpmnlD19CuqojhLT
    url:  jdbc:postgresql://db-nova-do-user-15129443-0.c.db.ondigitalocean.com:25060/nova_store
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: dilshodovfazliddin@gmail.com
    password: xkriwexxgzonkumt
    properties:
      mjaail:
        smtp:
          auth: true
      mail:
        smtp:
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

jwt:
  secret:
    key: 343243432432970943248034738493482742437324FG1
  access:
    expiry: 300000
  refresh:
    expiry: 300000
